# Generated by Django 5.0.7 on 2024-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
