# Generated by Django 5.0.7 on 2024-07-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webcam_project', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(upload_to='faces/'),
        ),
    ]
